class Transaction {
  final String id;
  final String roomId;
  final String type;
  final String? categoryId;
  final double amount;
  final String description;
  final DateTime date;
  final String status;
  final bool isAutoGenerated;
  final String? recurringId;
  final String? createdByDevice;
  final DateTime createdAt;
  final DateTime updatedAt;
  final String? categoryName;
  final String? categoryIcon;
  final String? categoryColor;

  Transaction({
    required this.id,
    required this.roomId,
    required this.type,
    this.categoryId,
    required this.amount,
    required this.description,
    required this.date,
    required this.status,
    this.isAutoGenerated = false,
    this.recurringId,
    this.createdByDevice,
    required this.createdAt,
    required this.updatedAt,
    this.categoryName,
    this.categoryIcon,
    this.categoryColor,
  });

  factory Transaction.fromJson(Map<String, dynamic> json) => Transaction(
    id: json['id'],
    roomId: json['room_id'],
    type: json['type'],
    categoryId: json['category_id'],
    amount: double.parse(json['amount'].toString()),
    description: json['description'] ?? '',
    date: DateTime.parse(json['date']),
    status: json['status'] ?? 'paid',
    isAutoGenerated: json['is_auto_generated'] ?? false,
    recurringId: json['recurring_id'],
    createdByDevice: json['created_by_device'],
    createdAt: DateTime.parse(json['created_at']),
    updatedAt: DateTime.parse(json['updated_at']),
    categoryName: json['category_name'],
    categoryIcon: json['category_icon'],
    categoryColor: json['category_color'],
  );
}

class ExpenseByCategory {
  final String id;
  final String name;
  final String icon;
  final String color;
  final double total;
  final int count;

  ExpenseByCategory({
    required this.id,
    required this.name,
    required this.icon,
    required this.color,
    required this.total,
    required this.count,
  });

  factory ExpenseByCategory.fromJson(Map<String, dynamic> json) => ExpenseByCategory(
    id: json['id'],
    name: json['name'],
    icon: json['icon'] ?? 'category',
    color: json['color'] ?? '#78909C',
    total: double.parse(json['total'].toString()),
    count: json['count'] ?? 0,
  );
}
