String _parseString(dynamic value, String fallback) {
  if (value == null) return fallback;
  return value.toString();
}

DateTime _parseDate(dynamic value) {
  if (value == null) return DateTime.now();
  return DateTime.parse(value.toString());
}

double _parseDouble(dynamic value) {
  if (value == null) return 0.0;
  return double.parse(value.toString());
}

class Transaction {
  final String id;
  final String roomId;
  final String type;
  final String? categoryId;
  final double amount;
  final String description;
  final DateTime date;
  final String status;
  final bool isAutoGenerated;
  final String? recurringId;
  final String? createdByDevice;
  final DateTime createdAt;
  final DateTime updatedAt;
  final String? categoryName;
  final String? categoryIcon;
  final String? categoryColor;

  Transaction({
    required this.id,
    required this.roomId,
    required this.type,
    this.categoryId,
    required this.amount,
    required this.description,
    required this.date,
    required this.status,
    this.isAutoGenerated = false,
    this.recurringId,
    this.createdByDevice,
    required this.createdAt,
    required this.updatedAt,
    this.categoryName,
    this.categoryIcon,
    this.categoryColor,
  });

  Transaction copyWith({
    String? id,
    String? roomId,
    String? type,
    String? categoryId,
    double? amount,
    String? description,
    DateTime? date,
    String? status,
    bool? isAutoGenerated,
    String? recurringId,
    String? createdByDevice,
    DateTime? createdAt,
    DateTime? updatedAt,
    String? categoryName,
    String? categoryIcon,
    String? categoryColor,
  }) => Transaction(
    id: id ?? this.id,
    roomId: roomId ?? this.roomId,
    type: type ?? this.type,
    categoryId: categoryId ?? this.categoryId,
    amount: amount ?? this.amount,
    description: description ?? this.description,
    date: date ?? this.date,
    status: status ?? this.status,
    isAutoGenerated: isAutoGenerated ?? this.isAutoGenerated,
    recurringId: recurringId ?? this.recurringId,
    createdByDevice: createdByDevice ?? this.createdByDevice,
    createdAt: createdAt ?? this.createdAt,
    updatedAt: updatedAt ?? this.updatedAt,
    categoryName: categoryName ?? this.categoryName,
    categoryIcon: categoryIcon ?? this.categoryIcon,
    categoryColor: categoryColor ?? this.categoryColor,
  );

  factory Transaction.fromJson(Map<String, dynamic> json) => Transaction(
    id: _parseString(json['id'], ''),
    roomId: _parseString(json['room_id'], ''),
    type: _parseString(json['type'], ''),
    categoryId: json['category_id']?.toString(),
    amount: _parseDouble(json['amount']),
    description: _parseString(json['description'], ''),
    date: _parseDate(json['date']),
    status: _parseString(json['status'], 'paid'),
    isAutoGenerated: json['is_auto_generated'] ?? false,
    recurringId: json['recurring_id']?.toString(),
    createdByDevice: json['created_by_device']?.toString(),
    createdAt: _parseDate(json['created_at']),
    updatedAt: _parseDate(json['updated_at']),
    categoryName: json['category_name']?.toString(),
    categoryIcon: json['category_icon']?.toString(),
    categoryColor: json['category_color']?.toString(),
  );
}

class ExpenseByCategory {
  final String id;
  final String name;
  final String icon;
  final String color;
  final double total;
  final int count;

  ExpenseByCategory({
    required this.id,
    required this.name,
    required this.icon,
    required this.color,
    required this.total,
    required this.count,
  });

  factory ExpenseByCategory.fromJson(Map<String, dynamic> json) => ExpenseByCategory(
    id: _parseString(json['id'], ''),
    name: _parseString(json['name'], ''),
    icon: _parseString(json['icon'], 'category'),
    color: _parseString(json['color'], '#78909C'),
    total: _parseDouble(json['total']),
    count: int.tryParse(json['count']?.toString() ?? '') ?? 0,
  );
}
